import type { LandingMessages, DashboardExtra, Messages, DocsMessages, IntegrationMessages, DocsLabels } from "./types";

export const label = "Deutsch";

export const dashboardExtra: DashboardExtra = { welcome: "Willkommen zurück", manage: "Server verwalten", yourServers: "Deine Server", status: "Aeris-Status", operational: "Betriebsbereit", attention: "Aufmerksamkeit erforderlich", members: "Mitglieder", viewAll: "Alle anzeigen →", noServers: "Noch keine Server", serverManagement: "Serververwaltung", selectServer: "Wähle einen Server, um seine Einstellungen zu verwalten" };

export const landing: LandingMessages = { eyebrow: "Discord-Bot für Ästhetik und Kontrolle", title: "Der Discord-Bot mit", highlight: "sauberen CV2-Oberflächen", description: "Automod, Leveling, Wirtschaft, Musik, Voicemaster, Tickets und Willkommensnachrichten — in einem minimalistischen Dashboard mit durchsuchbarer Dokumentation.", launch: "Aeris starten", readDocs: "Dokumentation lesen", features: [{ title: "Automod", text: "Wort- und Linkfilter, Spam-Erkennung und Raid-Schutz." }, { title: "Leveling", text: "XP-Tracking, Levelkarten, Rollenbelohnungen und Ranglisten." }, { title: "Wirtschaft", text: "Tägliche Belohnungen, Arbeit, Shop, Inventar, Blackjack und Handel." }, { title: "Musik", text: "Sprachwiedergabe mit Warteschlange und aktuellem Titel." }, { title: "Tickets", text: "Ticket-Erstellung, Transkripte, Teamzuweisung und Archivierung." }, { title: "Dokumentation", text: "Durchsuchbare Hilfe für Einrichtung, Berechtigungen und Fehlerbehebung." }], builtTitle: "Für eine klare Ästhetik gebaut", builtText: "CV2-Container, minimale Karten und ein Dashboard, das nicht im Weg steht und dennoch volle Kontrolle bietet.", checklist: ["Discord Components v2 statt veralteter Embeds", "Bildkarten für Level, Rangliste, Wirtschaft und Blackjack", "Helle und dunkle Themen nach Systemeinstellung", "Durchsuchbares Dokumentationszentrum"] };

export const messages: Messages = { overview: "Übersicht", servers: "Server", integrations: "Integrationen", docs: "Dokumentation", signOut: "Abmelden", signingOut: "Abmeldung…", toggleMenu: "Menü umschalten", language: "Sprache", chooseLanguage: "Sprache wählen", madeWithCare: "Aeris · Discord-Bot · Mit Sorgfalt erstellt", dashboard: "Dashboard", manageServers: "Verwalte deine Server und Aeris-Einstellungen", serverConfiguration: "Serverkonfiguration", saveChanges: "Änderungen speichern", saving: "Speichern…", saved: "Gespeichert", languageSetting: "Sprache", languageDescription: "Wähle die Sprache für Bot-Antworten auf diesem Server.", botLanguage: "Bot-Sprache", botLanguageDescription: "Diese Einstellung gilt für Befehle und automatische Nachrichten auf diesem Server.", selectLanguage: "Sprache auswählen", backToServers: "Zurück zu Servern" };

export const integration: IntegrationMessages = { eyebrow: "Verbundene Werkzeuge", title: "Integrationen", intro: "Nutze providerbasierte Abfragen und sichere Medienwerkzeuge an einem Ort.", minecraftPlayer: "Minecraft-Spieler", minecraftServer: "Minecraft-Server", robloxUser: "Roblox-Nutzer", movie: "Film oder Serie", usernamePlaceholder: "Notch", serverPlaceholder: "play.example.com", moviePlaceholder: "Interstellar", lookup: "Suchen", checkStatus: "Status prüfen", search: "Suchen", imageStudio: "Bildstudio", imageIntro: "Lokale Filter anwenden, ohne das Bild hochzuladen.", chooseImage: "Bild auswählen", original: "Original", grayscale: "Graustufen", sepia: "Sepia", invert: "Invertieren", download: "Herunterladen", selectImage: "Wähle ein Bild zur Vorschau aus.", lookupFailed: "Suche fehlgeschlagen. Bitte erneut versuchen.", imageAlt: "Bildvorschau", resultTitle: "Suchergebnis" };

export const docs: Partial<DocsMessages> = { eyebrow: "Aeris-Wissensdatenbank", title: "Dokumentation", intro: "Praktische Anleitungen für Einrichtung, Konfiguration, Berechtigungen und Serverbetrieb.", searchPlaceholder: "Anleitungen, Befehle oder Themen suchen…", allArticles: "Alle Artikel", backHome: "Zur Startseite", noResults: "Keine Anleitung gefunden. Versuche einen allgemeineren Begriff.", signInCta: "Bereit, deinen Server zu verwalten? Anmelden →", updated: "Für das aktuelle Aeris-Dashboard aktualisiert" };

export const articleOverrides: Record<string, Partial<DocsMessages["articles"][number]>> = {
    "getting-started": { title: "Erste Schritte", summary: "Richte einen neuen Server ein und prüfe jedes Modul mit einer klaren Checkliste.", content: "1. Melde dich mit Discord an und wähle einen Server, den du verwaltest.\n2. Lade Aeris aus der Serverübersicht ein und prüfe die angeforderten Berechtigungen.\n3. Wähle in den Servereinstellungen Sprache, Präfix, Log-Kanal und Module.\n4. Führe /bot info aus und teste je einen Befehl der aktivierten Module.\n\nCheckliste\n• Aeris muss in den vorgesehenen Kanälen sehen und schreiben können.\n• Das Aeris-Rolle muss über allen verwalteten Rollen stehen.\n• Richte vor automatischen Aktionen einen privaten Moderationskanal ein.\n• Prüfe externe Anbieter über Integrationen, ohne Schlüssel in Discord zu teilen." },
    "invite-permissions": { title: "Einladung und Berechtigungen", summary: "Gib nur die Berechtigungen frei, die deine aktivierten Module tatsächlich benötigen.", content: "Aeris funktioniert zuverlässiger mit einzelnen Berechtigungen als mit Administrator. Moderation benötigt Manage Messages, Moderate Members und je nach Aktion Kick Members, Ban Members und Manage Roles. Musik benötigt Connect und Speak; Tickets benötigen Manage Channels.\n\nDie Rollen-Hierarchie ist entscheidend: Discord blockiert Änderungen an Mitgliedern und Rollen, die gleich hoch oder höher als die Aeris-Rolle sind. Prüfe zusätzlich kanalbezogene Überschreibungen." },
    "release-checklist": { title: "Produktions-Checkliste", summary: "Prüfe Bot, API, Dashboard und Datenbank vor dem Start gemeinsam.", content: "Führe vor dem Start Typechecks aus, generiere Prisma-Typen und wende das Schema auf die Produktionsdatenbank an. Prüfe Token, OAuth-Weiterleitung, Sitzung, API-Ursprung und Provider im Deployment-Umfeld.\n\nNach dem Start: Health-Endpunkt prüfen, mit Discord anmelden, verwaltete Server bestätigen, /bot info ausführen und eine Moderationsaktion privat testen. Danach Logs, Lavalink und das Speichern der Serversprache prüfen." },
  };

export const docsLabels: Partial<DocsLabels> = { quickReference: "Kurzübersicht", implementationChecklist: "Umsetzungscheckliste", permissionMatrix: "Berechtigungsmatrix", capability: "Funktion", requiredPermission: "Benötigte Berechtigung", whyItMatters: "Warum wichtig" };
