import type { LandingMessages, DashboardExtra, Messages, DocsMessages, IntegrationMessages, DocsLabels } from "./types";

export const label = "English";

export const dashboardExtra: DashboardExtra = { welcome: "Welcome back", manage: "Manage Servers", yourServers: "Your Servers", status: "Aeris status", operational: "Operational", attention: "Needs attention", members: "Members", viewAll: "View all →", noServers: "No servers yet", serverManagement: "Server management", selectServer: "Select a server to manage its settings" };

export const landing: LandingMessages = { eyebrow: "Discord bot built for aesthetics and control", title: "The Discord bot with", highlight: "clean CV2 interfaces", description: "Automod, leveling, economy, music, voicemaster, tickets, and welcome messages — all surfaced through a minimal dashboard and search-powered docs.", launch: "Launch Aeris", readDocs: "Read the docs", features: [{ title: "Automod", text: "Word filters, link filters, spam detection, and raid protection." }, { title: "Leveling", text: "XP tracking, level-up image cards, role rewards, and leaderboards." }, { title: "Economy", text: "Daily rewards, work, shop, inventory, blackjack, and trades." }, { title: "Music", text: "Voice playback with queue management and now-playing." }, { title: "Tickets", text: "Ticket creation, transcripts, staff assignment, and close/archive." }, { title: "Docs Center", text: "Search-powered documentation for setup, permissions, and troubleshooting." }], builtTitle: "Built for a clean aesthetic", builtText: "CV2 containers, minimal cards, and a dashboard that stays out of your way while still giving you full control.", checklist: ["Discord Components v2 containers instead of legacy embeds", "Image cards for levelup, leaderboard, economy, and blackjack", "Light and dark themes that respect your system preference", "Search-powered documentation center"] };

export const messages: Messages = { overview: "Overview", servers: "Servers", integrations: "Integrations", docs: "Docs", signOut: "Sign out", signingOut: "Signing out…", toggleMenu: "Toggle menu", language: "Language", chooseLanguage: "Choose language", madeWithCare: "Aeris · Discord Bot · Made with care", dashboard: "Dashboard", manageServers: "Manage your servers and Aeris settings", serverConfiguration: "Server configuration", saveChanges: "Save changes", saving: "Saving…", saved: "Saved", languageSetting: "Language", languageDescription: "Choose the language Aeris uses for this server's bot responses.", botLanguage: "Bot language", botLanguageDescription: "This setting applies to commands and automated messages in this server.", selectLanguage: "Select a language", backToServers: "Back to servers" };

export const integration: IntegrationMessages = { eyebrow: "Connected tools", title: "Integrations", intro: "Run provider-backed lookups and browser-safe media tools from one workspace.", minecraftPlayer: "Minecraft player", minecraftServer: "Minecraft server", robloxUser: "Roblox user", movie: "Movie or TV", usernamePlaceholder: "Notch", serverPlaceholder: "play.example.com", moviePlaceholder: "Interstellar", lookup: "Look up", checkStatus: "Check status", search: "Search", imageStudio: "Image Studio", imageIntro: "Apply a local preview filter without uploading your image.", chooseImage: "Choose image", original: "Original", grayscale: "Grayscale", sepia: "Sepia", invert: "Invert", download: "Download", selectImage: "Select an image to preview it here.", lookupFailed: "Lookup failed. Please try again.", imageAlt: "Image preview", resultTitle: "Lookup result" };

export const docs: Partial<DocsMessages> = {};

export const articleOverrides: Record<string, Partial<DocsMessages["articles"][number]>> = {};

export const docsLabels: Partial<DocsLabels> = {};
