import type { LandingMessages, DashboardExtra, Messages, DocsMessages, IntegrationMessages, DocsLabels } from "./types";

export const label = "Español";

export const dashboardExtra: DashboardExtra = { welcome: "Bienvenido de nuevo", manage: "Administrar servidores", yourServers: "Tus servidores", status: "Estado de Aeris", operational: "Operativo", attention: "Requiere atención", members: "Miembros", viewAll: "Ver todos →", noServers: "Aún no hay servidores", serverManagement: "Administración de servidores", selectServer: "Selecciona un servidor para administrar su configuración" };

export const landing: LandingMessages = { eyebrow: "Bot de Discord creado para la estética y el control", title: "El bot de Discord con", highlight: "interfaces CV2 limpias", description: "Automod, niveles, economía, música, voicemaster, tickets y mensajes de bienvenida, todo desde un panel minimalista y documentación con búsqueda.", launch: "Abrir Aeris", readDocs: "Leer documentación", features: [{ title: "Automod", text: "Filtros de palabras y enlaces, detección de spam y protección contra raids." }, { title: "Niveles", text: "XP, tarjetas de nivel, recompensas de roles y clasificaciones." }, { title: "Economía", text: "Recompensas diarias, trabajos, tienda, inventario, blackjack e intercambios." }, { title: "Música", text: "Reproducción de voz con cola y canción actual." }, { title: "Tickets", text: "Creación de tickets, transcripciones, asignación y archivado." }, { title: "Documentación", text: "Documentación con búsqueda para configuración, permisos y solución de problemas." }], builtTitle: "Diseñado para una estética limpia", builtText: "Contenedores CV2, tarjetas minimalistas y un panel que no estorba, pero te da el control total.", checklist: ["Contenedores Discord Components v2 en lugar de embeds antiguos", "Tarjetas de imagen para niveles, clasificaciones, economía y blackjack", "Temas claro y oscuro que respetan tu sistema", "Centro de documentación con búsqueda"] };

export const messages: Messages = { overview: "Resumen", servers: "Servidores", integrations: "Integraciones", docs: "Documentación", signOut: "Cerrar sesión", signingOut: "Cerrando sesión…", toggleMenu: "Mostrar menú", language: "Idioma", chooseLanguage: "Elegir idioma", madeWithCare: "Aeris · Bot de Discord · Hecho con cuidado", dashboard: "Panel", manageServers: "Administra tus servidores y la configuración de Aeris", serverConfiguration: "Configuración del servidor", saveChanges: "Guardar cambios", saving: "Guardando…", saved: "Guardado", languageSetting: "Idioma", languageDescription: "Elige el idioma de las respuestas del bot en este servidor.", botLanguage: "Idioma del bot", botLanguageDescription: "Esta opción se aplica a los comandos y mensajes automáticos de este servidor.", selectLanguage: "Selecciona un idioma", backToServers: "Volver a servidores" };

export const integration: IntegrationMessages = { eyebrow: "Herramientas conectadas", title: "Integraciones", intro: "Usa búsquedas con proveedores y herramientas multimedia seguras desde un solo espacio.", minecraftPlayer: "Jugador de Minecraft", minecraftServer: "Servidor de Minecraft", robloxUser: "Usuario de Roblox", movie: "Película o serie", usernamePlaceholder: "Notch", serverPlaceholder: "play.example.com", moviePlaceholder: "Interstellar", lookup: "Buscar", checkStatus: "Comprobar estado", search: "Buscar", imageStudio: "Estudio de imágenes", imageIntro: "Aplica filtros locales sin subir tu imagen.", chooseImage: "Elegir imagen", original: "Original", grayscale: "Escala de grises", sepia: "Sepia", invert: "Invertir", download: "Descargar", selectImage: "Selecciona una imagen para previsualizarla.", lookupFailed: "La búsqueda falló. Inténtalo de nuevo.", imageAlt: "Vista previa", resultTitle: "Resultado" };

export const docs: Partial<DocsMessages> = { eyebrow: "Base de conocimiento de Aeris", title: "Documentación", intro: "Guías prácticas para configurar, proteger y administrar tu servidor.", searchPlaceholder: "Busca guías, comandos o temas…", allArticles: "Todos los artículos", backHome: "Volver al inicio", noResults: "No encontramos guías. Prueba un término más amplio o elige otra categoría.", signInCta: "¿Listo para administrar tu servidor? Inicia sesión →", updated: "Actualizado para el panel actual de Aeris" };

export const articleOverrides: Record<string, Partial<DocsMessages["articles"][number]>> = {
    "getting-started": { title: "Primeros pasos", summary: "Configura un servidor nuevo y valida cada módulo con una lista de comprobación clara.", content: "1. Inicia sesión con Discord y selecciona un servidor que administras.\n2. Invita Aeris desde el resumen del servidor y revisa los permisos solicitados.\n3. Abre Ajustes del servidor para elegir idioma, prefijo, canal de registros y módulos.\n4. Ejecuta /bot info y prueba un comando de cada módulo activo.\n\nLista de comprobación\n• Confirma que Aeris puede ver y escribir en los canales de comandos.\n• Coloca el rol de Aeris por encima de los roles que debe administrar.\n• Configura un canal privado de moderación antes de activar acciones automáticas.\n• Usa Integraciones para comprobar proveedores sin mostrar claves en Discord." },
    "invite-permissions": { title: "Invitación y permisos", summary: "Elige los permisos mínimos que necesitan tus módulos sin conceder acceso excesivo.", content: "Aeris funciona mejor con permisos explícitos que con Administrator. Moderación necesita Manage Messages, Moderate Members y, según la acción, Kick Members, Ban Members y Manage Roles. Música necesita Connect y Speak; tickets necesitan Manage Channels.\n\nLa jerarquía importa: Discord no permite que Aeris edite, asigne, silencie o sancione miembros cuyo rol más alto sea igual o superior al del bot. Revisa también las excepciones de permisos del canal." },
    "release-checklist": { title: "Lista de lanzamiento", summary: "Comprueba el bot, la API, el panel y la base de datos antes de publicar.", content: "Antes de publicar, ejecuta los typechecks, genera Prisma y aplica el esquema a la base de datos. Verifica token, OAuth, sesión, origen de la API y proveedores en el entorno de despliegue.\n\nDespués, abre el endpoint de salud, inicia sesión, confirma los servidores administrables, ejecuta /bot info y prueba una moderación en un canal privado. Comprueba también los registros, Lavalink y el guardado del idioma del servidor." },
  };

export const docsLabels: Partial<DocsLabels> = { quickReference: "Referencia rápida", implementationChecklist: "Lista de implementación", permissionMatrix: "Matriz de permisos", capability: "Capacidad", requiredPermission: "Permiso requerido", whyItMatters: "Por qué importa" };
