import type { LandingMessages, DashboardExtra, Messages, DocsMessages, IntegrationMessages, DocsLabels } from "./types";

export const label = "Français";

export const dashboardExtra: DashboardExtra = { welcome: "Bon retour", manage: "Gérer les serveurs", yourServers: "Vos serveurs", status: "État d’Aeris", operational: "Opérationnel", attention: "Attention requise", members: "Membres", viewAll: "Tout voir →", noServers: "Aucun serveur pour le moment", serverManagement: "Gestion des serveurs", selectServer: "Sélectionnez un serveur pour gérer ses réglages" };

export const landing: LandingMessages = { eyebrow: "Un bot Discord pensé pour l’esthétique et le contrôle", title: "Le bot Discord avec des", highlight: "interfaces CV2 épurées", description: "Automod, niveaux, économie, musique, voicemaster, tickets et messages de bienvenue dans un tableau de bord minimaliste avec documentation recherchable.", launch: "Lancer Aeris", readDocs: "Lire la documentation", features: [{ title: "Automod", text: "Filtres de mots et de liens, détection du spam et protection anti-raid." }, { title: "Niveaux", text: "XP, cartes de niveau, récompenses de rôles et classements." }, { title: "Économie", text: "Récompenses quotidiennes, travail, boutique, inventaire, blackjack et échanges." }, { title: "Musique", text: "Lecture vocale avec file d’attente et titre en cours." }, { title: "Tickets", text: "Création de tickets, transcriptions, attribution et archivage." }, { title: "Documentation", text: "Documentation recherchable pour la configuration, les permissions et le dépannage." }], builtTitle: "Pensé pour une esthétique épurée", builtText: "Conteneurs CV2, cartes minimalistes et tableau de bord discret qui vous laisse le contrôle.", checklist: ["Conteneurs Discord Components v2 au lieu des anciens embeds", "Cartes d’image pour les niveaux, classements, économie et blackjack", "Thèmes clair et sombre selon vos préférences système", "Centre de documentation avec recherche"] };

export const messages: Messages = { overview: "Aperçu", servers: "Serveurs", integrations: "Intégrations", docs: "Documentation", signOut: "Se déconnecter", signingOut: "Déconnexion…", toggleMenu: "Afficher le menu", language: "Langue", chooseLanguage: "Choisir la langue", madeWithCare: "Aeris · Bot Discord · Fait avec soin", dashboard: "Tableau de bord", manageServers: "Gérez vos serveurs et les réglages d'Aeris", serverConfiguration: "Configuration du serveur", saveChanges: "Enregistrer", saving: "Enregistrement…", saved: "Enregistré", languageSetting: "Langue", languageDescription: "Choisissez la langue des réponses du bot sur ce serveur.", botLanguage: "Langue du bot", botLanguageDescription: "Ce réglage s'applique aux commandes et messages automatiques de ce serveur.", selectLanguage: "Choisir une langue", backToServers: "Retour aux serveurs" };

export const integration: IntegrationMessages = { eyebrow: "Outils connectés", title: "Intégrations", intro: "Lancez des recherches avec fournisseurs et outils média sécurisés depuis un seul espace.", minecraftPlayer: "Joueur Minecraft", minecraftServer: "Serveur Minecraft", robloxUser: "Utilisateur Roblox", movie: "Film ou série", usernamePlaceholder: "Notch", serverPlaceholder: "play.example.com", moviePlaceholder: "Interstellar", lookup: "Rechercher", checkStatus: "Vérifier l’état", search: "Rechercher", imageStudio: "Studio d’image", imageIntro: "Appliquez un filtre local sans envoyer votre image.", chooseImage: "Choisir une image", original: "Original", grayscale: "Niveaux de gris", sepia: "Sépia", invert: "Inverser", download: "Télécharger", selectImage: "Sélectionnez une image pour la prévisualiser.", lookupFailed: "Échec de la recherche. Réessayez.", imageAlt: "Aperçu de l’image", resultTitle: "Résultat" };

export const docs: Partial<DocsMessages> = { eyebrow: "Base de connaissances Aeris", title: "Documentation", intro: "Guides pratiques pour configurer, sécuriser et administrer votre serveur.", searchPlaceholder: "Rechercher des guides, commandes ou sujets…", allArticles: "Tous les articles", backHome: "Retour à l’accueil", noResults: "Aucun guide ne correspond. Essayez un terme plus général.", signInCta: "Prêt à gérer votre serveur ? Se connecter →", updated: "Mis à jour pour le tableau de bord Aeris actuel" };

export const articleOverrides: Record<string, Partial<DocsMessages["articles"][number]>> = {
    "getting-started": { title: "Bien démarrer", summary: "Configurez un serveur et validez chaque module avec une checklist claire.", content: "1. Connectez-vous avec Discord et choisissez un serveur que vous gérez.\n2. Invitez Aeris depuis le résumé du serveur et vérifiez les permissions.\n3. Dans les réglages, choisissez la langue, le préfixe, le canal de logs et les modules.\n4. Lancez /bot info puis testez une commande de chaque module actif.\n\nChecklist\n• Aeris doit pouvoir voir et écrire dans les canaux concernés.\n• Placez son rôle au-dessus des rôles qu’il doit gérer.\n• Configurez un canal de modération privé avant les actions automatiques.\n• Validez les fournisseurs depuis Intégrations sans exposer de clés dans Discord." },
    "invite-permissions": { title: "Invitation et permissions", summary: "Accordez les permissions nécessaires sans donner un accès excessif.", content: "Aeris est plus sûr avec des permissions précises qu’avec Administrator. La modération utilise Manage Messages, Moderate Members et selon l’action Kick Members, Ban Members ou Manage Roles. La musique utilise Connect et Speak; les tickets utilisent Manage Channels.\n\nLa hiérarchie des rôles est obligatoire: Discord bloque les actions sur les membres et rôles placés au même niveau ou au-dessus d’Aeris. Vérifiez aussi les permissions propres au canal." },
    "release-checklist": { title: "Checklist de mise en production", summary: "Validez le bot, l’API, le tableau de bord et la base avant la publication.", content: "Avant la mise en ligne, lancez les vérifications TypeScript, générez Prisma et appliquez le schéma à la base de production. Vérifiez le token, OAuth, la session, l’origine API et les fournisseurs dans l’environnement de déploiement.\n\nAprès publication, testez la santé de l’API, la connexion Discord, la liste des serveurs, /bot info, une action de modération privée, les logs, Lavalink et l’enregistrement de la langue du serveur." },
  };

export const docsLabels: Partial<DocsLabels> = { quickReference: "Référence rapide", implementationChecklist: "Checklist de mise en œuvre", permissionMatrix: "Matrice des permissions", capability: "Fonction", requiredPermission: "Permission requise", whyItMatters: "Pourquoi c’est important" };
