import type { LandingMessages, DashboardExtra, Messages, DocsMessages, IntegrationMessages, DocsLabels } from "./types";

export const label = "Hindi";

export const dashboardExtra: DashboardExtra = { welcome: "Wapsi par swagat hai", manage: "Server prabandhit karein", yourServers: "Aapke server", status: "Aeris sthiti", operational: "Sakriya", attention: "Dhyan avashyak", members: "Sadasya", viewAll: "Sabhi dekhein →", noServers: "Abhi koi server nahi", serverManagement: "Server prabandhan", selectServer: "Setting prabandhit karne ke liye server chunein" };

export const landing: LandingMessages = { eyebrow: "Sundarta aur niyantran ke liye banaya gaya Discord bot", title: "Saaf CV2 interface wala", highlight: "Discord bot", description: "Automod, leveling, arthavyavastha, sangeet, voicemaster, tickets aur welcome sandesh — ek saral dashboard aur khoj yogya dastavejon ke saath.", launch: "Aeris shuru karein", readDocs: "Dastavej padhein", features: [{ title: "Automod", text: "Shabd aur link filter, spam detection aur raid suraksha." }, { title: "Leveling", text: "XP tracking, level card, role reward aur leaderboard." }, { title: "Arthavyavastha", text: "Dainik puraskar, kaam, dukaan, inventory, blackjack aur trade." }, { title: "Sangeet", text: "Queue aur vartaman gaane ke saath voice playback." }, { title: "Tickets", text: "Ticket banana, transcripts, staff assignment aur archive." }, { title: "Dastavej Kendra", text: "Setup, permissions aur samasya samadhan ke liye khoj yogya dastavej." }], builtTitle: "Saaf design ke liye banaya gaya", builtText: "CV2 containers, minimal cards aur aisa dashboard jo raaste mein nahi aata, phir bhi poora niyantran deta hai.", checklist: ["Purane embeds ki jagah Discord Components v2 containers", "Level, leaderboard, economy aur blackjack ke liye image cards", "System preference ke anusaar light aur dark themes", "Khoj yogya documentation center"] };

export const messages: Messages = { overview: "Avalokan", servers: "Server", integrations: "Integration", docs: "Dastavej", signOut: "Sign out", signingOut: "Sign out ho raha hai…", toggleMenu: "Menu badlein", language: "Bhasha", chooseLanguage: "Bhasha chunein", madeWithCare: "Aeris · Discord bot · Savdhani se banaya gaya", dashboard: "Dashboard", manageServers: "Apne server aur Aeris setting prabandhit karein", serverConfiguration: "Server configuration", saveChanges: "Badlaav sahejein", saving: "Saheja ja raha hai…", saved: "Saheja gaya", languageSetting: "Bhasha", languageDescription: "Is server mein bot pratikriyaon ki bhasha chunein.", botLanguage: "Bot bhasha", botLanguageDescription: "Yah setting is server ke command aur swachalit sandeshon par lagu hoti hai.", selectLanguage: "Bhasha chunein", backToServers: "Server par wapas jayein" };

export const integration: IntegrationMessages = { eyebrow: "Connected tools", title: "Integration", intro: "Ek hi workspace se provider lookups aur surakshit media tools chalayein.", minecraftPlayer: "Minecraft khiladi", minecraftServer: "Minecraft server", robloxUser: "Roblox upyogakarta", movie: "Film ya TV", usernamePlaceholder: "Notch", serverPlaceholder: "play.example.com", moviePlaceholder: "Interstellar", lookup: "Khojein", checkStatus: "Sthiti jaanchein", search: "Khojein", imageStudio: "Image Studio", imageIntro: "Image upload kiye bina local filter lagayein.", chooseImage: "Image chunein", original: "Mool", grayscale: "Grayscale", sepia: "Sepia", invert: "Invert", download: "Download", selectImage: "Preview ke liye image chunein.", lookupFailed: "Lookup vifal hua. Phir prayas karein.", imageAlt: "Image preview", resultTitle: "Lookup parinaam" };

export const docs: Partial<DocsMessages> = { eyebrow: "Aeris Gyaan Kendra", title: "Dastavej", intro: "Setup, configuration, permissions aur server management ke liye upyogi guides.", searchPlaceholder: "Guide, command ya vishay khojein…", allArticles: "Sabhi lekh", backHome: "Home par jayein", noResults: "Koi guide nahi mila. Vyapak shabd se khojein.", signInCta: "Server prabandhit karne ke liye taiyaar hain? Sign in karein →", updated: "Vartaman Aeris dashboard ke liye update kiya gaya" };

export const articleOverrides: Record<string, Partial<DocsMessages["articles"][number]>> = {
    "getting-started": { title: "Shuruaat kaise karein", summary: "Naye server ko set karein aur spasht checklist se har module ki jaanch karein.", content: "1. Discord se sign in karke apna managed server chunein.\n2. Server overview se Aeris ko invite karein aur permissions jaanchein.\n3. Server settings mein language, prefix, log channel aur modules chunein.\n4. /bot info chalayein aur har enabled module ka ek command test karein.\n\nChecklist\n• Aeris ko command channels mein view aur send permissions dein.\n• Aeris role ko managed roles se upar rakhein.\n• Automatic actions se pehle private moderation log channel banayein.\n• Keys Discord mein dikhaye bina Integrations se providers jaanchein." },
    "invite-permissions": { title: "Invite aur permissions", summary: "Sirf wahi permissions dein jinki enabled modules ko avashyakta hai.", content: "Administrator dene ke bajay Aeris ko spasht permissions dein. Moderation ke liye Manage Messages, Moderate Members aur zaroorat ke anusaar Kick Members, Ban Members, Manage Roles chahiye. Music ke liye Connect aur Speak tatha tickets ke liye Manage Channels chahiye.\n\nRole hierarchy avashyak hai: Aeris samaan ya upar ke roles wale members ya roles ko badal nahi sakta. Channel-specific permission overwrites bhi jaanchein." },
    "release-checklist": { title: "Production launch checklist", summary: "Publish karne se pehle bot, API, dashboard aur database ki jaanch karein.", content: "Launch se pehle typechecks chalayein, Prisma types generate karein aur production database mein schema lagu karein. Deployment environment mein token, OAuth redirect, session, API origin aur provider keys jaanchein.\n\nLaunch ke baad health endpoint, Discord login, managed server list, /bot info aur private moderation action test karein. Logs, Lavalink aur server language save bhi verify karein." },
  };

export const docsLabels: Partial<DocsLabels> = { quickReference: "Twarit sandarbh", implementationChecklist: "Implementation checklist", permissionMatrix: "Permission matrix", capability: "Capability", requiredPermission: "Required permission", whyItMatters: "Kyon zaroori hai" };
