import type { LandingMessages, DashboardExtra, Messages, DocsMessages, IntegrationMessages, DocsLabels } from "./types";

export const label = "Русский";

export const dashboardExtra: DashboardExtra = { welcome: "С возвращением", manage: "Управлять серверами", yourServers: "Ваши серверы", status: "Статус Aeris", operational: "Работает", attention: "Требуется внимание", members: "Участники", viewAll: "Показать все →", noServers: "Серверов пока нет", serverManagement: "Управление серверами", selectServer: "Выберите сервер для управления настройками" };

export const landing: LandingMessages = { eyebrow: "Discord-бот для эстетики и полного контроля", title: "Discord-бот с", highlight: "чистыми CV2-интерфейсами", description: "Автомодерация, уровни, экономика, музыка, voicemaster, тикеты и приветствия — в минималистичной панели с документацией и поиском.", launch: "Запустить Aeris", readDocs: "Открыть документацию", features: [{ title: "Автомодерация", text: "Фильтры слов и ссылок, защита от спама и рейдов." }, { title: "Уровни", text: "XP, карточки уровней, награды ролями и рейтинги." }, { title: "Экономика", text: "Ежедневные награды, работа, магазин, инвентарь, blackjack и обмен." }, { title: "Музыка", text: "Воспроизведение с очередью и текущим треком." }, { title: "Тикеты", text: "Создание тикетов, транскрипты, назначение сотрудников и архивирование." }, { title: "Документация", text: "Поиск по настройке, разрешениям и устранению проблем." }], builtTitle: "Создан для чистой эстетики", builtText: "CV2-контейнеры, минималистичные карточки и панель, которая не мешает, но даёт полный контроль.", checklist: ["Discord Components v2 вместо устаревших embeds", "Карточки изображений для уровней, рейтингов, экономики и blackjack", "Светлая и тёмная темы с учётом настроек системы", "Центр документации с поиском"] };

export const messages: Messages = { overview: "Обзор", servers: "Серверы", integrations: "Интеграции", docs: "Документация", signOut: "Выйти", signingOut: "Выход…", toggleMenu: "Открыть меню", language: "Язык", chooseLanguage: "Выбрать язык", madeWithCare: "Aeris · Бот Discord · Сделано с заботой", dashboard: "Панель управления", manageServers: "Управляйте серверами и настройками Aeris", serverConfiguration: "Настройки сервера", saveChanges: "Сохранить изменения", saving: "Сохранение…", saved: "Сохранено", languageSetting: "Язык", languageDescription: "Выберите язык ответов бота на этом сервере.", botLanguage: "Язык бота", botLanguageDescription: "Настройка применяется к командам и автоматическим сообщениям этого сервера.", selectLanguage: "Выберите язык", backToServers: "Назад к серверам" };

export const integration: IntegrationMessages = { eyebrow: "Подключённые инструменты", title: "Интеграции", intro: "Запускайте запросы к провайдерам и безопасные медиа-инструменты из одного рабочего пространства.", minecraftPlayer: "Игрок Minecraft", minecraftServer: "Сервер Minecraft", robloxUser: "Пользователь Roblox", movie: "Фильм или сериал", usernamePlaceholder: "Notch", serverPlaceholder: "play.example.com", moviePlaceholder: "Interstellar", lookup: "Найти", checkStatus: "Проверить статус", search: "Поиск", imageStudio: "Студия изображений", imageIntro: "Применяйте локальные фильтры без загрузки изображения.", chooseImage: "Выбрать изображение", original: "Оригинал", grayscale: "Оттенки серого", sepia: "Сепия", invert: "Инверсия", download: "Скачать", selectImage: "Выберите изображение для предпросмотра.", lookupFailed: "Поиск не удался. Попробуйте ещё раз.", imageAlt: "Предпросмотр изображения", resultTitle: "Результат поиска" };

export const docs: Partial<DocsMessages> = { eyebrow: "База знаний Aeris", title: "Документация", intro: "Практические руководства по настройке, разрешениям и ежедневному управлению сервером.", searchPlaceholder: "Поиск руководств, команд или тем…", allArticles: "Все статьи", backHome: "На главную", noResults: "Руководства не найдены. Попробуйте более общий запрос.", signInCta: "Готовы управлять сервером? Войти →", updated: "Обновлено для текущей панели Aeris" };

export const articleOverrides: Record<string, Partial<DocsMessages["articles"][number]>> = {
    "getting-started": { title: "Начало работы", summary: "Настройте сервер и проверьте каждый модуль по понятному списку действий.", content: "1. Войдите через Discord и выберите сервер, которым управляете.\n2. Пригласите Aeris из обзора сервера и проверьте разрешения.\n3. В настройках выберите язык, префикс, канал журналов и модули.\n4. Выполните /bot info и проверьте по одной команде каждого модуля.\n\nЧеклист\n• Aeris должен видеть и отправлять сообщения в нужных каналах.\n• Роль Aeris должна быть выше ролей, которыми она управляет.\n• Создайте закрытый канал модерации до включения автоматических действий.\n• Проверяйте провайдеров через Интеграции, не публикуя ключи в Discord." },
    "invite-permissions": { title: "Приглашение и разрешения", summary: "Выдайте только те разрешения, которые нужны включённым модулям.", content: "Точные разрешения безопаснее, чем Administrator. Модерации нужны Manage Messages, Moderate Members и, в зависимости от действия, Kick Members, Ban Members и Manage Roles. Музыке нужны Connect и Speak, тикетам — Manage Channels.\n\nИерархия ролей обязательна: Discord не разрешит Aeris менять участников и роли на том же или более высоком уровне. Проверьте также ограничения конкретного канала." },
    "release-checklist": { title: "Чеклист запуска", summary: "Проверьте бота, API, панель и базу данных перед публикацией.", content: "Перед запуском выполните typecheck, сгенерируйте Prisma и примените схему к production-базе. Проверьте token, OAuth redirect, session, API origin и провайдеров в окружении деплоя.\n\nПосле запуска проверьте health endpoint, вход через Discord, список серверов, /bot info, приватное действие модерации, логи, Lavalink и сохранение языка сервера." },
  };

export const docsLabels: Partial<DocsLabels> = { quickReference: "Краткая справка", implementationChecklist: "Чеклист внедрения", permissionMatrix: "Матрица разрешений", capability: "Возможность", requiredPermission: "Требуемое разрешение", whyItMatters: "Зачем это нужно" };
